version: '3'
services:
  postgres:
    image: postgres:12
    build:
      context: ./docker/
      dockerfile: Dockerfile.postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_USER=postgres
      - POSTGRES_DB=urlshortener
    volumes:
      - ./migration:/var/lib/postgresql/data

#  server:
#    build:
#      context: ./docker/
#      dockerfile: Dockerfile.server
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      POSTGRESQL_HOST: postgres
#    links:
#      - postgres