version: '3.3'
services:
  postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=urlshortener

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    #command: ./wait-for-postgres.sh db ./main
    #restart: always
    ports:
      - "8080:8080"
    environment:
      - POSTGRESQL_HOST=postgres
      - POSTGRES_PASSWORD=12345678
    links:
      - postgres