version: '3.3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: ./wait-for-postgres.sh db ./main
    #restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_HOST=db

  db:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=urlshortener
